version: '3'
services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx